### PR TITLE
in exercises w05, encourage students to try Pos.moved and reflect over results

### PR DESCRIPTION
**Pull request by snctfd**
This is a first draft to solve #678. Feedback welcome!

I have not yet managed to compile the compendium to ensure that this looks good.

### CODE REVIEW

**Comment by bjornregnell** [comment]
I can merge and compile after review (currently you need old latex as installed in 20.04 or later or else allslides.tex fails). I will review this soon.

**Comment by bjornregnell** [comment]
This looks great. It would be good if can add some text with explanation in the subtask solution as well?

**Comment by snctfd** [comment]
> Classes don't have methods, only objects and class instances do, strictly speaking...

Good catch - I was a little uncertain as to what the specific terminology should be, I've changed it in accordance with your suggestion. 

I've also added an initial draft for an explanation to the solution. Remaining concerns:
* I feel like the wording of the explanation could be improved, but after writing out several variants this was about the best I could do. Thoughts, suggestions?
* As it is, I've put the explanation as a new SubtaskSolved, seeing as the existing TaskSolved for all of task 6 was just "Denna uppgift är laborationsförberedelse. Utvärdera dina lösningar genom egna tester i REPL.". Is this okay? Should I add some sort of context for what question my explanation is answering?
* As I understand it, you typically put errors in `\code` tags. I initially tried this with my text, but as the error message I listed is quite long and starts near the end of the line, this simply caused most of the text to disappear off the screen. For now, I instead put the error message in quotes, and simply `\code`-tagged `moved` and `Pos`. Is there a better solution?

**Comment by bjornregnell** [comment]
LGTM

**Comment by bjornregnell** [comment]
I will add "[till en referens] till klassen"

**Comment by snctfd** [comment]
Oh yeah, that makes sense :)

**Comment by bjornregnell** [comment]
https://github.com/lunduniversity/introprog/commit/603f70d24a0f3692c0a664e996626b66bdd2894f

**Comment by bjornregnell** [comment]
many thanks for discovering and fixing this!

**Pull request merged**
