### PR TITLE
update workflow file

### PR DESCRIPTION
**Pull request by fritjof-b**
- Improve readability
- Add functionality to manually trigger workflow
- Rename job
- Run on two latest Ubuntu LTS
- Boilerplate for uploading PDF artifacts generated by build

### CODE REVIEW

**Comment by bjornregnell** [comment]
Many thanks!

**Comment by bjornregnell** [comment]
You have question in the main.yml file by the end i an comment regarding the path. 

Where should it be uploaded? Is there a special artifact place under the repo created then on github or something? How are credentials or login handled or this is not needed?

**Comment by fritjof-b** [comment]
No credentials needed. GH actions has its own store for artefacts (in this case PDFs). So when the build completes, you should be able to navigate to something like `Actions > Build > Artifacts > {foo.pdf, bar.pdf}`

So the idea was that if a build succeeds, we can view the generated compendium from that build. It's a minor thing, I was just unsure of where the PDFs are placed once generated since I was playing around in the Github environment on my fork... :-)

**Comment by bjornregnell** [comment]
Ok great! Feel free to test with whatever path you think is necessary and let me know if I need to configure something as repo owner.

**Pull request merged**
