### PR TITLE
Fix #475 added missing definition for r

### LINKED ISSUE #475: Typo in assignment 18, chapter 2.2.3
There's a typo on the second line in the listed code. It states: `val sekvens = r.toArray` and r is never defined.

### PR DESCRIPTION
**Pull request by wudse20**
Fix for #475, the missing defintion for r has been added, based on the answer in chapter L.2.3.

### CODE REVIEW

**Comment by emmanuelkring** [comment]
I think the original mistake here was to write `r` instead of `intervall`. It can be fixed in the following way:
> scala> val intervall = (1 to Int.MaxValue by 2)
scala> val sekvens = intervall.toArray

**Comment by wudse20** [comment]
This PR should cover your fix, which is better.

**Review by jos-rosenqvist-3812 — APPROVED** [review]
The commit history of this pull request would look nicer if the commits were squashed into one and the merge commit was removed: https://stackoverflow.com/questions/30561895/removing-merge-commits-in-git/30565914

However, this can be tricky to do if you don't already have a lot of experience with git, so alternatively we could merge the pull request as-is. Please let us know if this is something you would like to do before the pull request gets merged.

**Comment by wudse20** [comment]
The merge commit should now be removed.

**Pull request merged**
