### PR TITLE
Fix appendix typos and other minor problems

### PR DESCRIPTION
**Pull request by jos-rosenqvist-3812**

### CODE REVIEW

**Comment by bjornregnell** [comment]
Many thanks for all these commits! I'm wondering what is best wrt spacing:
http://tex.stackexchange.com/questions/116528/vs-after-abbreviation-read-backslash-at-vs-backslash-space
Perhaps the \sbt macro should be redefined instead to \newcommand{\sbt}{\texttt{sbt}\@} if I understood the above Q&A correctly.

**Comment by jos-rosenqvist-3812** [comment]
I'll try that out after the weekend.

If I'm going to edit the PR, do you want me to edit the old commit and force push, or just add a new commit? (I'm fine with either.)

**Comment by bjornregnell** [comment]
Thanks! Just add a new commit; I'll merge all your existing PR:s in consecutive order during the weekend.

**Comment by jos-rosenqvist-3812** [comment]
The `\@` is used for forcing inter-sentence spacing after a period. We don't have a period here, so there doesn't seem to be any point to using `\@`. (Does Swedish even use different spacing inside sentences than between sentences?)

**Comment by bjornregnell** [comment]
Ok, good; then we skip \@; but it would be nice to define \sbt so that \sbt\ is not needed if possible. Or we just keep it as is now.

**Pull request merged**
