### PR TITLE
Removed "new" keyword from w04-objects-exercise.tex

### PR DESCRIPTION
**Pull request by OlofBen**
New should not be used in Scala, except for in factory methods right?

### CODE REVIEW

**Comment by bjornregnell** [comment]
Well "should" is a bit strong. It's rather that you can skip it if you want.

**Comment by bjornregnell** [comment]
I'm hesitating if we should keep new or not in this exercise as it makes the allocation explicit and it is a prequel to next week's theme on classes. What do you think? We could keep new here and add a comment or so that new can be skipped.

**Comment by OlofBen** [comment]
You've got a point. However, the students have not seen the "new" keyword yet, so I think it can be a bit confusing for a new student.

**Comment by bjornregnell** [comment]
Yes they have - there is a part during the lectures about classes as a prequel in week objects before next week on classes, and the see with and without new etc, and we talk about allocation on the heap and draw clouds etc.

**Comment by bjornregnell** [comment]
Ok great. It is good if tutors explain what new does during exercises.

**Pull request closed without merging**
