### PR TITLE
Fix chapter 3 typos

### PR DESCRIPTION
**Pull request by Husenap**
* Fixed a couple of typos in lab preparations

### CODE REVIEW

**Comment by bjornregnell** [comment]
Thanks for looking into this. Yes if we deprecate underscore then we need to go through the whole compendium and slides as I think they might be in several places... Would be nice if you could investigate the impact before going with a thunk.
I think we should properly introduce the term "thunk" in the `function` week and make a separate slide on that.
https://en.wikipedia.org/wiki/Thunk

**Comment by Husenap** [comment]
How about I leave it out of this PR and only keep the typo fixes, then I can create an issue where we can discuss it further?

**Comment by bjornregnell** [comment]
Yes, good to separate typos and the longer stuff!

**Comment by bjornregnell** [comment]
There are alot of formatting changes, so it is easy to miss other changes when reviewing. Are all the indents from the original file?  Usually I dont use indents in the latex code as there are often unwanted side effects of those...

**Comment by bjornregnell** [comment]
Ah. I was looking at an old page - now when refreshing in browser the changes look nicer and only a few. Cool!

**Comment by bjornregnell** [comment]
Is this ready for merge?

**Comment by bjornregnell** [comment]
Looks Good To Me.

**Pull request merged**
