### PR TITLE
fix typos in lab w01

### PR DESCRIPTION
**Pull request by Zolomon**
Fixed all typos I could find in this file.

Should I add all recompiled PDF files to commits of this kind now and in the future?

### CODE REVIEW

**Comment by bjornregnell** [comment]
Thanks! No, don't add pdfs: keep the PR clean with an as small change set as possible/reasonable as motivated the fixed file(s). I'll do the recompile after merge and push pdfs. But good that you verified that it compiles before creating a PR! You can check out your changes to your pdf before you synch your fork to avoid conflicts.

**Comment by bjornregnell** [comment]
I added an explanation in relation to your Q in README under how to contribute; pls check to see if it now might help more.

**Comment by Zolomon** [comment]
It looks quite clear, IMHO.

Thanks!

**Comment by Zolomon** [comment]
It just occurred to me that maybe a comment similar to would be good to give concrete examples: 

"To see examples of acceptable PR:s, take a look at [previously accepted ones](https://github.com/lunduniversity/introprog/pulls?q=is%3Apr+is%3Aclosed)."

**Comment by bjornregnell** [comment]
Good idea! PR on README.md welcome! ;)

**Pull request merged**
