### PR TITLE
Update solutions w12 Threads

### PR DESCRIPTION
**Pull request by annasjovall**
Solution for the basic tasks

### CODE REVIEW

**Comment by bjornregnell** [comment]
This PR does not compile. Please check Details link above and scroll to the very end of the log, where you will find this:
```
[482]) (./modules/w12-solutions.tex [483]
! Extra }, or forgotten \endgroup.
l.31 \Subtask Funktionen \{printLater}
                                       har en \code{Future}, vilket innebär...
```
Can you fix it based on this info?

**Comment by bjornregnell** [comment]
Edit "Details *below*"
Or just follow this link:
https://travis-ci.org/lunduniversity/introprog/builds/153216925#L4462

**Comment by bjornregnell** [comment]
BTW: Why did you commit a change in .gitignore for the lthopoly lab?

**Comment by annasjovall** [comment]
Hahah den måste ha slunkit med. Var inte meningen.

Den 18 aug. 2016 12:01 em skrev Bjorn Regnell <notifications@github.com>:

BTW: Why did you commit a change in .gitignore for the lthopoly lab?

**Pull request closed without merging**
