### PR TITLE
Changed "uniform access" to "enhetlig access (eng. uniform access)"

### PR DESCRIPTION
**Pull request by EdvinGroth**

### CODE REVIEW

**Comment by bjornregnell** [comment]
Have you built it locally and checked that the line does not overflow?

**Comment by EdvinGroth** [comment]
I did not build it locally since i do not have a latex compiler. I tried doing it in overleaf but i reached the compile time limit so i couldnt check it there either since i also thought it might disrupt how the table looks. I will just remove the translation and try making a new pull request.

**Comment by EdvinGroth** [comment]
It seems like it updates the pull request automatically so i won't make a new one, correct me if i'm wrong.

**Comment by bjornregnell** [comment]
connected to #663

**Pull request merged**
