### PR TITLE
quickref: Fix typos

### PR DESCRIPTION
**Pull request by sadphi**
Fixed some typos that I found in quickref. Also changed `call` to be in plural (`recursive call` -> `recursive calls`).

### CODE REVIEW

**Comment by bjornregnell** [comment]
Sorry I just saw this *after* fixing some of your comments already. based on input from gitter https://gitter.im/scala/contributors?at=61218aeaeb72173430dcb60a

Could you, in order to avoid merge conflicts, please change this PR so it just include the changes that are new compared to my latest commits?

**Comment by sadphi** [comment]
Perfect timing :smile:. It seems to only be the change to plural in `recursive call` that's conflicting, so I'll revert that change.

**Comment by sadphi** [comment]
Fixed in latest commit

**Comment by bjornregnell** [comment]
ok, closing this, just fixed calls here https://github.com/lunduniversity/introprog/commit/94ae214d9006767fd54197cd23710a8170f695fc

**Pull request merged**
