### PR TITLE
update lab w12 description. Changed incorrect names of methods. 

### PR DESCRIPTION
**Pull request by JonasDe**
Clarified actions, getAction, getPossibleActions

### CODE REVIEW

**Comment by jos-rosenqvist-3812** [comment]
What is meant by "Därefter kan ni anropa metoden TextUI.promptForInput för att återge standardvyn ovanför"? Isn't the default view printed by updateConsole, not TextUI.promptForInput? Or does "default view" refer to a combination of the log, status and selectable actions, not just the log and status?

**Comment by JonasDe** [comment]
>
> What is meant by "Därefter kan ni anropa metoden TextUI.promptForInput för
> att återge standardvyn ovanför"? Isn't the default view printed by
> updateConsole, not TextUI.promptForInput? Or does "default view" refer to a
> combination of the log, status and selectable actions, not just the log and
> status?
>
Hi Jos!

The default view should be the full view *including *the selectable
actions, the one displayed by REPL-figure.
I did push a change that included (in the other picture of the REPL) the
actions when displaying the game-board view as well, but it seems they
haven't gotten into the compendium (just downloaded it, I guess it has to
be recompiled?).
Both views should show all actions, but the default view should also show
the status window and log, the other should just print the gameboard view.

/Jonas




2016-12-04 22:42 GMT+01:00 Jos Rosenqvist <notifications@github.com>:

**Comment by bjornregnell** [comment]
Hi; sorry missed to recompile compendium.pdf -- it turned out that parallel changes caused conflicts that were unresolved; I hope I have fixed them now. @JonasDe could you check so that your changes are intact (so that I didn't accidentally resolve the conflict with old stuff...)

**Comment by JonasDe** [comment]
Yeah it's looking good, it all seems to be there! 
I clarified what was asked for by @jos-rosenqvist-3812  and sent another pull request. Happy recompiling :)

**Comment by bjornregnell** [comment]
Many thanks; I'm on it! Always fun to compile :)

**Pull request merged**
