### PR TITLE
fix todo excercise 6.14

### PR DESCRIPTION
**Pull request by axelnilsson98**
fixed a todo in excercise acording to #758. Not certain about what formatting you want on the answer so leave a comment if you like me to change something

### CODE REVIEW

**Comment by bjornregnell** [comment]
Sorry for the delay in my review. Maybe change "Contains" till `Metoden \code{contains}` to get the capitalization right and show code font ?

**Comment by axelnilsson98** [comment]
Sounds good. I have now updated the pull request

**Comment by bjornregnell** [comment]
Unfortunately this code did not compile... but I found the problem after some time:  https://github.com/lunduniversity/introprog/commit/423b7d3524b66c6468f94b2bff9e24a518717a66

**Comment by bjornregnell** [comment]
Always compile before committing... @axelnilsson98

**Comment by axelnilsson98** [comment]
sorry, I will be more thorough in the future. Good that you found it.

**Pull request merged**
